baseURL = "https://next-docs.lisenhui.cn"
theme = "zzodoc"

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

copyright = "MIT&copy; elkan1788"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

googleAnalytics = "G-FRZ5KLPGPL"

disableKinds = ["taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  tag = "tags"
