[zh]
  title = "NexT主题文档"
  languageName = "中文"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/zh"
  
[en]
   title = "Z Themes Documentation"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"